In [1]:
%%capture
!pip install autogluon.tabular scikit-learn==1.5.2 "ray>=2.10.0,<2.45.0"

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from autogluon.tabular import TabularPredictor

import warnings
warnings.filterwarnings('ignore')

In [3]:
# LOAD DATA
categorical_features = ['road_type', 'lighting', 'weather', 'road_signs_present', 'public_road', 'time_of_day', 'holiday', 'school_season']
train_df = pd.read_csv(r'/kaggle/input/playground-series-s5e10/train.csv').drop(columns = 'id')
train_df = pd.get_dummies(train_df, columns=categorical_features, prefix_sep='_', drop_first=False)
test_df  = pd.read_csv(r'/kaggle/input/playground-series-s5e10/test.csv').drop(columns = 'id')
test_df = pd.get_dummies(test_df, columns=categorical_features, prefix_sep='_', drop_first=False)

In [4]:
# AUTOGLUON

# DEFINE AUTOGLUON
predictor = TabularPredictor(label = 'accident_risk',
                         problem_type = 'regression',
                         eval_metric = 'rmse')

# TRAIN AUTOGLUON
predictor.fit(train_df,
              presets = 'extreme',
              num_cpus = 1,
              verbosity = 2,
              ag_args_fit={'num_gpus': 1})

No path specified. Models will be saved in: "AutogluonModels/ag-20251005_120429"
Preset alias specified: 'extreme' maps to 'extreme_quality'.
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.4.0
Python Version:     3.11.13
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP PREEMPT_DYNAMIC Sun Nov 10 10:07:59 UTC 2024
CPU Count:          4
Memory Avail:       30.01 GB / 31.35 GB (95.7%)
Disk Space Avail:   19.50 GB / 19.52 GB (99.9%)
===================================================
Presets specified: ['extreme']
`extreme` preset uses a dynamic portfolio based on dataset size...
	Detected data size: large (>30000 samples), using `zeroshot` portfolio (identical to 'best_quality' preset).
Using hyperparameters preset: hyperparameters='zeroshot'
Setting dynamic_stacking from 'auto' to True. Reason: Enable dynamic_stacking when use_bag_holdout is disabled. (use_bag_holdout=False)
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=8, num_bag_sets=1
DyStack is enabled (dynamic_stacking=True). AutoGluon will try to determine whether the input data is affected by stacked overfitting and enable or disable stacking as a consequence.
	This is used to identify the optimal `num_stack_levels` value. Copies of AutoGluon will be fit on subsets of the data. Then holdout validation data is used to detect stacked overfitting.
	Running DyStack for up to 900s of the 3600s of remaining time (25%).
	Running DyStack sub-fit in a ray process to avoid memory leakage. Enabling ray logging (enable_ray_logging=True). Specify `ds_args={'enable_ray_logging': False}` if you experience logging issues.
2025-10-05 12:04:32,015	INFO worker.py:1852 -- Started a local Ray instance.
		Context path: "/kaggle/working/AutogluonModels/ag-20251005_120429/ds_sub_fit/sub_fit_ho"
(_dystack pid=178) Running DyStack sub-fit ...
(_dystack pid=178) Beginning AutoGluon training ... Time limit = 896s
(_dystack pid=178) AutoGluon will save models to "/kaggle/working/AutogluonModels/ag-20251005_120429/ds_sub_fit/sub_fit_ho"
(_dystack pid=178) Train Data Rows:    460225
(_dystack pid=178) Train Data Columns: 24
(_dystack pid=178) Label Column:       accident_risk
(_dystack pid=178) Problem Type:       regression
(_dystack pid=178) Preprocessing data ...
(_dystack pid=178) Using Feature Generators to preprocess the data ...
(_dystack pid=178) Fitting AutoMLPipelineFeatureGenerator...
(_dystack pid=178) 	Available Memory:                    29866.14 MB
(_dystack pid=178) 	Train Data (Original)  Memory Usage: 22.82 MB (0.1% of available memory)
(_dystack pid=178) 	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
(_dystack pid=178) 	Stage 1 Generators:
(_dystack pid=178) 		Fitting AsTypeFeatureGenerator...
(_dystack pid=178) 			Note: Converting 20 features to boolean dtype as they only contain 2 unique values.
(_dystack pid=178) 	Stage 2 Generators:
(_dystack pid=178) 		Fitting FillNaFeatureGenerator...
(_dystack pid=178) 	Stage 3 Generators:
(_dystack pid=178) 		Fitting IdentityFeatureGenerator...
(_dystack pid=178) 	Stage 4 Generators:
(_dystack pid=178) 		Fitting DropUniqueFeatureGenerator...
(_dystack pid=178) 	Stage 5 Generators:
(_dystack pid=178) 		Fitting DropDuplicatesFeatureGenerator...
(_dystack pid=178) 	Types of features in original data (raw dtype, special dtypes):
(_dystack pid=178) 		('bool', [])  : 20 | ['road_type_highway', 'road_type_rural', 'road_type_urban', 'lighting_daylight', 'lighting_dim', ...]
(_dystack pid=178) 		('float', []) :  1 | ['curvature']
(_dystack pid=178) 		('int', [])   :  3 | ['num_lanes', 'speed_limit', 'num_reported_accidents']
(_dystack pid=178) 	Types of features in processed data (raw dtype, special dtypes):
(_dystack pid=178) 		('float', [])     :  1 | ['curvature']
(_dystack pid=178) 		('int', [])       :  3 | ['num_lanes', 'speed_limit', 'num_reported_accidents']
(_dystack pid=178) 		('int', ['bool']) : 20 | ['road_type_highway', 'road_type_rural', 'road_type_urban', 'lighting_daylight', 'lighting_dim', ...]
(_dystack pid=178) 	0.9s = Fit runtime
(_dystack pid=178) 	24 features in original data used to generate 24 features in processed data.
(_dystack pid=178) 	Train Data (Processed) Memory Usage: 22.82 MB (0.1% of available memory)
(_dystack pid=178) Data preprocessing and feature engineering runtime = 0.91s ...
(_dystack pid=178) AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
(_dystack pid=178) 	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
(_dystack pid=178) 	To change this, specify the eval_metric parameter of Predictor()
(_dystack pid=178) Large model count detected (110 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
(_dystack pid=178) User-specified model hyperparameters to be fit:
(_dystack pid=178) {
(_dystack pid=178) 	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
(_dystack pid=178) 	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
(_dystack pid=178) 	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
(_dystack pid=178) 	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
(_dystack pid=178) 	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
(_dystack pid=178) 	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
(_dystack pid=178) 	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
(_dystack pid=178) }
(_dystack pid=178) AutoGluon will fit 2 stack levels (L1 to L2) ...
(_dystack pid=178) Fitting 106 L1 models, fit_strategy="sequential" ...
(_dystack pid=178) Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 596.44s of the 894.87s of remaining time.
(_dystack pid=178) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (1 workers, per: cpus=1, gpus=1, memory=0.60%)
(_ray_fit pid=181) 	Training S1F1 with GPU, note that this may negatively impact model quality compared to CPU training.
(_ray_fit pid=181) 1 warning generated.
(_ray_fit pid=181) 1 warning generated.
(_ray_fit pid=181) 1 warning generated.
(_ray_fit pid=181) 1 warning generated.
(_ray_fit pid=181) 1 warning generated.
(_ray_fit pid=181) 1 warning generated.
(_ray_fit pid=181) 1 warning generated.
(_ray_fit pid=181) 1 warning generated.
(_ray_fit pid=181) 1 warning generated.
(_ray_fit pid=181) 1 warning generated.
(_ray_fit pid=181) 1 warning generated.
(_ray_fit pid=181) 1 warning generated.
(_ray_fit pid=181) 1 warning generated.
(_ray_fit pid=181) 1 warning generated.
(_ray_fit pid=181) 1 warning generated.
(_ray_fit pid=181) 1 warning generated.
(_ray_fit pid=181) 1 warning generated.
(_ray_fit pid=181) 1 warning generated.
(_ray_fit pid=181) 1 warning generated.
(_ray_fit pid=181) 1 warning generated.
(_ray_fit pid=181) 1 warning generated.
(_ray_fit pid=181) 1 warning generated.
(_ray_fit pid=181) 1 warning generated.
(_ray_fit pid=181) 1 warning generated.
(_ray_fit pid=181) 1 warning generated.
(_ray_fit pid=181) 1 warning generated.
(_ray_fit pid=181) 1 warning generated.
(_ray_fit pid=181) 1 warning generated.
(_ray_fit pid=181) 1 warning generated.
(_ray_fit pid=181) 1 warning generated.
(_ray_fit pid=181) 1 warning generated.
(_ray_fit pid=181) 1 warning generated.
(_ray_fit pid=181) 1 warning generated.

(_ray_fit pid=181) [1000]	valid_set's rmse: 0.0564822
(_ray_fit pid=181) [2000]	valid_set's rmse: 0.0564643

(_ray_fit pid=179) 	Training S1F2 with GPU, note that this may negatively impact model quality compared to CPU training.

(_ray_fit pid=179) [1000]	valid_set's rmse: 0.0566445

(_ray_fit pid=180) 	Training S1F3 with GPU, note that this may negatively impact model quality compared to CPU training.

(_ray_fit pid=180) [1000]	valid_set's rmse: 0.0569656
(_ray_fit pid=180) [2000]	valid_set's rmse: 0.0569484

(_ray_fit pid=524) 	Training S1F4 with GPU, note that this may negatively impact model quality compared to CPU training.

(_ray_fit pid=524) [1000]	valid_set's rmse: 0.0562849

(_ray_fit pid=563) 	Training S1F5 with GPU, note that this may negatively impact model quality compared to CPU training.

(_ray_fit pid=563) [1000]	valid_set's rmse: 0.056211
(_ray_fit pid=563) [2000]	valid_set's rmse: 0.0561939

(_ray_fit pid=602) 	Training S1F6 with GPU, note that this may negatively impact model quality compared to CPU training.

(_ray_fit pid=602) [1000]	valid_set's rmse: 0.0559615

(_ray_fit pid=641) 	Training S1F7 with GPU, note that this may negatively impact model quality compared to CPU training.

(_ray_fit pid=641) [1000]	valid_set's rmse: 0.0566386
(_ray_fit pid=641) [2000]	valid_set's rmse: 0.0566053

(_ray_fit pid=680) 	Training S1F8 with GPU, note that this may negatively impact model quality compared to CPU training.

(_ray_fit pid=680) [1000]	valid_set's rmse: 0.0564001

(_dystack pid=178) 	-0.0564	 = Validation score   (-root_mean_squared_error)
(_dystack pid=178) 	292.02s	 = Training   runtime
(_dystack pid=178) 	60.42s	 = Validation runtime
(_dystack pid=178) Fitting model: LightGBM_BAG_L1 ... Training model for up to 291.09s of the 589.53s of remaining time.
(_dystack pid=178) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (1 workers, per: cpus=1, gpus=1, memory=0.61%)
(_ray_fit pid=771) 	Training S1F1 with GPU, note that this may negatively impact model quality compared to CPU training.

(_ray_fit pid=771) [1000]	valid_set's rmse: 0.0561084

(_ray_fit pid=774) 	Training S1F2 with GPU, note that this may negatively impact model quality compared to CPU training.

(_ray_fit pid=774) [1000]	valid_set's rmse: 0.0563256

(_ray_fit pid=887) 	Training S1F3 with GPU, note that this may negatively impact model quality compared to CPU training.

(_ray_fit pid=887) [1000]	valid_set's rmse: 0.0566188

(_ray_fit pid=926) 	Training S1F4 with GPU, note that this may negatively impact model quality compared to CPU training.

(_ray_fit pid=926) [1000]	valid_set's rmse: 0.0559917

(_ray_fit pid=965) 	Training S1F5 with GPU, note that this may negatively impact model quality compared to CPU training.
(_ray_fit pid=1004) 	Training S1F6 with GPU, note that this may negatively impact model quality compared to CPU training.

(_ray_fit pid=1004) [1000]	valid_set's rmse: 0.0556101

(_ray_fit pid=1043) 	Training S1F7 with GPU, note that this may negatively impact model quality compared to CPU training.
(_ray_fit pid=1082) 	Training S1F8 with GPU, note that this may negatively impact model quality compared to CPU training.
(_dystack pid=178) 	-0.0561	 = Validation score   (-root_mean_squared_error)
(_dystack pid=178) 	151.27s	 = Training   runtime
(_dystack pid=178) 	23.59s	 = Validation runtime
(_dystack pid=178) Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 135.75s of the 434.18s of remaining time.
(_dystack pid=178) 	Warning: Reducing model 'n_estimators' from 300 -> 172 due to low time. Expected time usage reduced from 235.1s -> 135.6s...
(_dystack pid=178) 	-0.0567	 = Validation score   (-root_mean_squared_error)
(_dystack pid=178) 	119.73s	 = Training   runtime
(_dystack pid=178) 	8.82s	 = Validation runtime
(_dystack pid=178) Fitting model: CatBoost_BAG_L1 ... Training model for up to 6.39s of the 304.82s of remaining time.
(_dystack pid=178) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (1 workers, per: cpus=1, gpus=1, memory=1.93%)
(_dystack pid=178) 	Time limit exceeded... Skipping CatBoost_BAG_L1.
(_ray_fit pid=1203) 	Training S1F1 with GPU, note that this may negatively impact model quality compared to CPU training.
(_ray_fit pid=1203) 	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
(_dystack pid=178) Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 3.18s of the 301.61s of remaining time.
(_dystack pid=178) 	Warning: Model is expected to require 206.5s to train, which exceeds the maximum time limit of 3.0s, skipping model...
(_dystack pid=178) 	Time limit exceeded... Skipping ExtraTreesMSE_BAG_L1.
(_dystack pid=178) Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 0.10s of the 298.53s of remaining time.
(_dystack pid=178) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (1 workers, per: cpus=1, gpus=1, memory=1.00%)
(_dystack pid=178) 	Time limit exceeded... Skipping NeuralNetFastAI_BAG_L1.
(_dystack pid=178) Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 298.13s of remaining time.
(_dystack pid=178) 	Ensemble Weights: {'LightGBM_BAG_L1': 0.75, 'RandomForestMSE_BAG_L1': 0.188, 'LightGBMXT_BAG_L1': 0.062}
(_dystack pid=178) 	-0.0561	 = Validation score   (-root_mean_squared_error)
(_dystack pid=178) 	0.25s	 = Training   runtime
(_dystack pid=178) 	0.01s	 = Validation runtime
(_dystack pid=178) Fitting 106 L2 models, fit_strategy="sequential" ...
(_dystack pid=178) Fitting model: LightGBMXT_BAG_L2 ... Training model for up to 297.84s of the 297.80s of remaining time.
(_dystack pid=178) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (1 workers, per: cpus=1, gpus=1, memory=0.72%)
(_ray_fit pid=1196) 	Training S1F1 with GPU, note that this may negatively impact model quality compared to CPU training.

(_ray_fit pid=1196) [1000]	valid_set's rmse: 0.0562882
(_ray_fit pid=1196) [2000]	valid_set's rmse: 0.0562991

(_ray_fit pid=1411) 	Training S1F2 with GPU, note that this may negatively impact model quality compared to CPU training.

(_ray_fit pid=1411) [1000]	valid_set's rmse: 0.056116

(_ray_fit pid=1489) 	Training S1F3 with GPU, note that this may negatively impact model quality compared to CPU training.

(_ray_fit pid=1489) [1000]	valid_set's rmse: 0.0562928

(_ray_fit pid=1528) 	Training S1F4 with GPU, note that this may negatively impact model quality compared to CPU training.
(_ray_fit pid=1567) 	Training S1F5 with GPU, note that this may negatively impact model quality compared to CPU training.

(_ray_fit pid=1567) [1000]	valid_set's rmse: 0.0560406

(_ray_fit pid=1606) 	Training S1F6 with GPU, note that this may negatively impact model quality compared to CPU training.
(_ray_fit pid=1645) 	Training S1F7 with GPU, note that this may negatively impact model quality compared to CPU training.
(_ray_fit pid=1684) 	Training S1F8 with GPU, note that this may negatively impact model quality compared to CPU training.

(_ray_fit pid=1684) [1000]	valid_set's rmse: 0.0560254

(_dystack pid=178) 	-0.0562	 = Validation score   (-root_mean_squared_error)
(_dystack pid=178) 	169.08s	 = Training   runtime
(_dystack pid=178) 	30.38s	 = Validation runtime
(_dystack pid=178) Fitting model: LightGBM_BAG_L2 ... Training model for up to 122.27s of the 122.24s of remaining time.
(_dystack pid=178) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (1 workers, per: cpus=1, gpus=1, memory=0.72%)
(_ray_fit pid=1781) 	Training S1F1 with GPU, note that this may negatively impact model quality compared to CPU training.
(_ray_fit pid=1784) 	Training S1F2 with GPU, note that this may negatively impact model quality compared to CPU training.
(_ray_fit pid=1897) 	Training S1F3 with GPU, note that this may negatively impact model quality compared to CPU training.
(_ray_fit pid=1936) 	Training S1F4 with GPU, note that this may negatively impact model quality compared to CPU training.
(_ray_fit pid=1975) 	Training S1F5 with GPU, note that this may negatively impact model quality compared to CPU training.
(_ray_fit pid=2014) 	Training S1F6 with GPU, note that this may negatively impact model quality compared to CPU training.
(_ray_fit pid=2053) 	Training S1F7 with GPU, note that this may negatively impact model quality compared to CPU training.
(_ray_fit pid=2092) 	Training S1F8 with GPU, note that this may negatively impact model quality compared to CPU training.
(_dystack pid=178) 	-0.056	 = Validation score   (-root_mean_squared_error)
(_dystack pid=178) 	67.52s	 = Training   runtime
(_dystack pid=178) 	4.22s	 = Validation runtime
(_dystack pid=178) Fitting model: RandomForestMSE_BAG_L2 ... Training model for up to 52.00s of the 51.97s of remaining time.
(_dystack pid=178) 	Warning: Model is expected to require 586.7s to train, which exceeds the maximum time limit of 51.8s, skipping model...
(_dystack pid=178) 	Time limit exceeded... Skipping RandomForestMSE_BAG_L2.
(_dystack pid=178) Fitting model: CatBoost_BAG_L2 ... Training model for up to 43.79s of the 43.75s of remaining time.
(_dystack pid=178) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (1 workers, per: cpus=1, gpus=1, memory=2.06%)
(_ray_fit pid=2205) 	Training S1F1 with GPU, note that this may negatively impact model quality compared to CPU training.
(_ray_fit pid=2205) 	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
(_dystack pid=178) Failed to unpickle serialized exception
(_dystack pid=178) Traceback (most recent call last):
(_dystack pid=178)   File "/usr/local/lib/python3.11/dist-packages/ray/exceptions.py", line 51, in from_ray_exception
(_dystack pid=178)     return pickle.loads(ray_exception.serialized_exception)
(_dystack pid=178)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=178) ModuleNotFoundError: No module named '_catboost'
(_dystack pid=178)
(_dystack pid=178) The above exception was the direct cause of the following exception:
(_dystack pid=178)
(_dystack pid=178) Traceback (most recent call last):
(_dystack pid=178)   File "/usr/local/lib/python3.11/dist-packages/ray/_private/serialization.py", line 460, in deserialize_objects
(_dystack pid=178)     obj = self._deserialize_object(data, metadata, object_ref)
(_dystack pid=178)           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=178)   File "/usr/local/lib/python3.11/dist-packages/ray/_private/serialization.py", line 342, in _deserialize_object
(_dystack pid=178)     return RayError.from_bytes(obj)
(_dystack pid=178)            ^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=178)   File "/usr/local/lib/python3.11/dist-packages/ray/exceptions.py", line 45, in from_bytes
(_dystack pid=178)     return RayError.from_ray_exception(ray_exception)
(_dystack pid=178)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=178)   File "/usr/local/lib/python3.11/dist-packages/ray/exceptions.py", line 54, in from_ray_exception
(_dystack pid=178)     raise RuntimeError(msg) from e
(_dystack pid=178) RuntimeError: Failed to unpickle serialized exception
(_dystack pid=178) 	Warning: Exception caused CatBoost_BAG_L2 to fail during training... Skipping this model.
(_dystack pid=178) 		System error: Failed to unpickle serialized exception
(_dystack pid=178) traceback: Traceback (most recent call last):
(_dystack pid=178)   File "/usr/local/lib/python3.11/dist-packages/ray/exceptions.py", line 51, in from_ray_exception
(_dystack pid=178)     return pickle.loads(ray_exception.serialized_exception)
(_dystack pid=178)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=178) ModuleNotFoundError: No module named '_catboost'
(_dystack pid=178)
(_dystack pid=178) The above exception was the direct cause of the following exception:
(_dystack pid=178)
(_dystack pid=178) Traceback (most recent call last):
(_dystack pid=178)   File "/usr/local/lib/python3.11/dist-packages/ray/_private/serialization.py", line 460, in deserialize_objects
(_dystack pid=178)     obj = self._deserialize_object(data, metadata, object_ref)
(_dystack pid=178)           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=178)   File "/usr/local/lib/python3.11/dist-packages/ray/_private/serialization.py", line 342, in _deserialize_object
(_dystack pid=178)     return RayError.from_bytes(obj)
(_dystack pid=178)            ^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=178)   File "/usr/local/lib/python3.11/dist-packages/ray/exceptions.py", line 45, in from_bytes
(_dystack pid=178)     return RayError.from_ray_exception(ray_exception)
(_dystack pid=178)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=178)   File "/usr/local/lib/python3.11/dist-packages/ray/exceptions.py", line 54, in from_ray_exception
(_dystack pid=178)     raise RuntimeError(msg) from e
(_dystack pid=178) RuntimeError: Failed to unpickle serialized exception
(_dystack pid=178)
(_dystack pid=178) Detailed Traceback:
(_dystack pid=178) Traceback (most recent call last):
(_dystack pid=178)   File "/usr/local/lib/python3.11/dist-packages/autogluon/tabular/trainer/abstract_trainer.py", line 2171, in _train_and_save
(_dystack pid=178)     model = self._train_single(**model_fit_kwargs)
(_dystack pid=178)             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=178)   File "/usr/local/lib/python3.11/dist-packages/autogluon/tabular/trainer/abstract_trainer.py", line 2055, in _train_single
(_dystack pid=178)     model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, X_test=X_test, y_test=y_test, total_resources=total_resources, **model_fit_kwargs)
(_dystack pid=178)             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=178)   File "/usr/local/lib/python3.11/dist-packages/autogluon/core/models/abstract/abstract_model.py", line 1068, in fit
(_dystack pid=178)     out = self._fit(**kwargs)
(_dystack pid=178)           ^^^^^^^^^^^^^^^^^^^
(_dystack pid=178)   File "/usr/local/lib/python3.11/dist-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py", line 270, in _fit
(_dystack pid=178)     return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)
(_dystack pid=178)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=178)   File "/usr/local/lib/python3.11/dist-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py", line 389, in _fit
(_dystack pid=178)     self._fit_folds(
(_dystack pid=178)   File "/usr/local/lib/python3.11/dist-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py", line 868, in _fit_folds
(_dystack pid=178)     fold_fitting_strategy.after_all_folds_scheduled()
(_dystack pid=178)   File "/usr/local/lib/python3.11/dist-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py", line 723, in after_all_folds_scheduled
(_dystack pid=178)     self._run_parallel(X, y, X_pseudo, y_pseudo, model_base_ref, time_limit_fold, head_node_id)
(_dystack pid=178)   File "/usr/local/lib/python3.11/dist-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py", line 664, in _run_parallel
(_dystack pid=178)     self._process_fold_results(finished, unfinished, fold_ctx)
(_dystack pid=178)   File "/usr/local/lib/python3.11/dist-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py", line 620, in _process_fold_results
(_dystack pid=178)     raise processed_exception
(_dystack pid=178)   File "/usr/local/lib/python3.11/dist-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py", line 583, in _process_fold_results
(_dystack pid=178)     fold_model, pred_proba, time_start_fit, time_end_fit, predict_time, predict_1_time, predict_n_size, fit_num_cpus, fit_num_gpus = self.ray.get(finished)
(_dystack pid=178)                                                                                                                                      ^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=178)   File "/usr/local/lib/python3.11/dist-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
(_dystack pid=178)     return fn(*args, **kwargs)
(_dystack pid=178)            ^^^^^^^^^^^^^^^^^^^
(_dystack pid=178)   File "/usr/local/lib/python3.11/dist-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
(_dystack pid=178)     return func(*args, **kwargs)
(_dystack pid=178)            ^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=178)   File "/usr/local/lib/python3.11/dist-packages/ray/_private/worker.py", line 2782, in get
(_dystack pid=178)     values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
(_dystack pid=178)                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=178)   File "/usr/local/lib/python3.11/dist-packages/ray/_private/worker.py", line 931, in get_objects
(_dystack pid=178)     raise value
(_dystack pid=178) ray.exceptions.RaySystemError: System error: Failed to unpickle serialized exception
(_dystack pid=178) traceback: Traceback (most recent call last):
(_dystack pid=178)   File "/usr/local/lib/python3.11/dist-packages/ray/exceptions.py", line 51, in from_ray_exception
(_dystack pid=178)     return pickle.loads(ray_exception.serialized_exception)
(_dystack pid=178)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=178) ModuleNotFoundError: No module named '_catboost'
(_dystack pid=178)
(_dystack pid=178) The above exception was the direct cause of the following exception:
(_dystack pid=178)
(_dystack pid=178) Traceback (most recent call last):
(_dystack pid=178)   File "/usr/local/lib/python3.11/dist-packages/ray/_private/serialization.py", line 460, in deserialize_objects
(_dystack pid=178)     obj = self._deserialize_object(data, metadata, object_ref)
(_dystack pid=178)           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=178)   File "/usr/local/lib/python3.11/dist-packages/ray/_private/serialization.py", line 342, in _deserialize_object
(_dystack pid=178)     return RayError.from_bytes(obj)
(_dystack pid=178)            ^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=178)   File "/usr/local/lib/python3.11/dist-packages/ray/exceptions.py", line 45, in from_bytes
(_dystack pid=178)     return RayError.from_ray_exception(ray_exception)
(_dystack pid=178)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=178)   File "/usr/local/lib/python3.11/dist-packages/ray/exceptions.py", line 54, in from_ray_exception
(_dystack pid=178)     raise RuntimeError(msg) from e
(_dystack pid=178) RuntimeError: Failed to unpickle serialized exception
(_dystack pid=178)
(_dystack pid=178) Fitting model: ExtraTreesMSE_BAG_L2 ... Training model for up to 27.37s of the 27.34s of remaining time.
(_dystack pid=178) 	Warning: Model is expected to require 270.5s to train, which exceeds the maximum time limit of 27.1s, skipping model...
(_dystack pid=178) 	Time limit exceeded... Skipping ExtraTreesMSE_BAG_L2.
(_dystack pid=178) Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.
(_dystack pid=178) Fitting model: NeuralNetFastAI_BAG_L2 ... Training model for up to 23.35s of the 23.32s of remaining time.
(_dystack pid=178) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (1 workers, per: cpus=1, gpus=1, memory=1.20%)
(_dystack pid=178) 	Time limit exceeded... Skipping NeuralNetFastAI_BAG_L2.
(_dystack pid=178) Fitting model: XGBoost_BAG_L2 ... Training model for up to 14.42s of the 14.38s of remaining time.
(_dystack pid=178) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (1 workers, per: cpus=1, gpus=1, memory=0.96%)
(_ray_fit pid=2373) /usr/local/lib/python3.11/dist-packages/xgboost/core.py:160: UserWarning: [12:19:21] WARNING: /workspace/src/common/error_msg.cc:58: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
(_ray_fit pid=2373) Potential solutions:
(_ray_fit pid=2373) - Use a data structure that matches the device ordinal in the booster.
(_ray_fit pid=2373) - Set the device for booster before call to inplace_predict.
(_ray_fit pid=2373)
(_ray_fit pid=2373) This warning will only be shown once.
(_ray_fit pid=2373)
(_ray_fit pid=2373)   warnings.warn(smsg, UserWarning)
(_ray_fit pid=2544)
(_ray_fit pid=2544)
(_ray_fit pid=2612)
(_ray_fit pid=2612)
(_ray_fit pid=2612) /usr/local/lib/python3.11/dist-packages/xgboost/core.py:160: UserWarning: [12:19:27] WARNING: /workspace/src/common/error_msg.cc:58: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu. [repeated 2x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#log-deduplication for more options.)
(_ray_fit pid=2612) Potential solutions: [repeated 2x across cluster]
(_ray_fit pid=2612) - Use a data structure that matches the device ordinal in the booster. [repeated 2x across cluster]
(_ray_fit pid=2612) - Set the device for booster before call to inplace_predict. [repeated 2x across cluster]
(_ray_fit pid=2612) This warning will only be shown once. [repeated 2x across cluster]
(_ray_fit pid=2612)   warnings.warn(smsg, UserWarning) [repeated 2x across cluster]
(_ray_fit pid=2645)
(_ray_fit pid=2645)
(_ray_fit pid=2678)
(_ray_fit pid=2678)
(_ray_fit pid=2678) /usr/local/lib/python3.11/dist-packages/xgboost/core.py:160: UserWarning: [12:19:34] WARNING: /workspace/src/common/error_msg.cc:58: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu. [repeated 2x across cluster]
(_ray_fit pid=2678) Potential solutions: [repeated 2x across cluster]
(_ray_fit pid=2678) - Use a data structure that matches the device ordinal in the booster. [repeated 2x across cluster]
(_ray_fit pid=2678) - Set the device for booster before call to inplace_predict. [repeated 2x across cluster]
(_ray_fit pid=2678) This warning will only be shown once. [repeated 2x across cluster]
(_ray_fit pid=2678)   warnings.warn(smsg, UserWarning) [repeated 2x across cluster]
(_ray_fit pid=2711)
(_ray_fit pid=2711)
(_ray_fit pid=2744)
(_ray_fit pid=2744)
(_ray_fit pid=2744) /usr/local/lib/python3.11/dist-packages/xgboost/core.py:160: UserWarning: [12:19:41] WARNING: /workspace/src/common/error_msg.cc:58: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu. [repeated 2x across cluster]
(_ray_fit pid=2744) Potential solutions: [repeated 2x across cluster]
(_ray_fit pid=2744) - Use a data structure that matches the device ordinal in the booster. [repeated 2x across cluster]
(_ray_fit pid=2744) - Set the device for booster before call to inplace_predict. [repeated 2x across cluster]
(_ray_fit pid=2744) This warning will only be shown once. [repeated 2x across cluster]
(_ray_fit pid=2744)   warnings.warn(smsg, UserWarning) [repeated 2x across cluster]
(_ray_fit pid=2777)
(_ray_fit pid=2777)
(_dystack pid=178) 	-0.1502	 = Validation score   (-root_mean_squared_error)
(_dystack pid=178) 	25.24s	 = Training   runtime
(_dystack pid=178) 	0.52s	 = Validation runtime
(_dystack pid=178) Fitting model: WeightedEnsemble_L3 ... Training model for up to 360.00s of the -12.89s of remaining time.
(_dystack pid=178) 	Ensemble Weights: {'LightGBM_BAG_L2': 0.688, 'LightGBM_BAG_L1': 0.25, 'RandomForestMSE_BAG_L1': 0.062}
(_dystack pid=178) 	-0.056	 = Validation score   (-root_mean_squared_error)
(_dystack pid=178) 	0.45s	 = Training   runtime
(_dystack pid=178) 	0.01s	 = Validation runtime
(_dystack pid=178) AutoGluon training complete, total runtime = 909.21s ... Best model: WeightedEnsemble_L3 | Estimated inference throughput: 643.9 rows/s (57529 batch size)
(_dystack pid=178) TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/kaggle/working/AutogluonModels/ag-20251005_120429/ds_sub_fit/sub_fit_ho")
(_dystack pid=178) Deleting DyStack predictor artifacts (clean_up_fits=True) ...
(_ray_fit pid=2777) /usr/local/lib/python3.11/dist-packages/xgboost/core.py:160: UserWarning: [12:19:44] WARNING: /workspace/src/common/error_msg.cc:58: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
(_ray_fit pid=2777) Potential solutions:
(_ray_fit pid=2777) - Use a data structure that matches the device ordinal in the booster.
(_ray_fit pid=2777) - Set the device for booster before call to inplace_predict.
(_ray_fit pid=2777) This warning will only be shown once.
(_ray_fit pid=2777)   warnings.warn(smsg, UserWarning)
Leaderboard on holdout data (DyStack):
                    model  score_holdout  score_val              eval_metric  pred_time_test  pred_time_val    fit_time  pred_time_test_marginal  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0     WeightedEnsemble_L3      -0.055907  -0.056025  root_mean_squared_error       85.162361      97.059817  630.987889                 0.003074                0.007437           0.445154            3       True          8
1         LightGBM_BAG_L2      -0.055917  -0.056033  root_mean_squared_error       85.159287      97.052379  630.542735                 4.219765                4.223235          67.519734            2       True          6
2     WeightedEnsemble_L2      -0.055930  -0.056070  root_mean_squared_error       80.942713      92.836695  563.274367                 0.003191                0.007550           0.251366            2       True          4
3         LightGBM_BAG_L1      -0.055964  -0.056107  root_mean_squared_error       23.093870      23.594857  151.270427                23.093870               23.594857         151.270427            1       True          2
4       LightGBMXT_BAG_L2      -0.055987  -0.056189  root_mean_squared_error      110.349116     123.212333  732.099102                29.409594               30.383189         169.076101            2       True          5
5       LightGBMXT_BAG_L1      -0.056257  -0.056431  root_mean_squared_error       56.597536      60.418132  292.018914                56.597536               60.418132         292.018914            1       True          1

In [5]:
predictor.leaderboard()

,model,score_val,eval_metric,pred_time_val,fit_time,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,WeightedEnsemble_L3,-0.055930,root_mean_squared_error,173.664301,2300.794502,0.009925,0.777619,3,True,13
1,LightGBM_BAG_L2,-0.055977,root_mean_squared_error,160.797384,1731.004340,5.268705,79.921474,2,True,11
2,WeightedEnsemble_L2,-0.055991,root_mean_squared_error,54.425463,548.127249,0.008563,0.618238,2,True,9
3,LightGBMLarge_BAG_L1,-0.056026,root_mean_squared_error,7.545125,101.793604,7.545125,101.793604,1,True,8
4,XGBoost_BAG_L1,-0.056075,root_mean_squared_error,0.561578,37.183168,0.561578,37.183168,1,True,7
5,LightGBMXT_BAG_L2,-0.056080,root_mean_squared_error,183.854506,1823.434516,28.325828,172.351650,2,True,10
6,LightGBM_BAG_L1,-0.056085,root_mean_squared_error,29.486737,172.658030,29.486737,172.658030,1,True,2
7,RandomForestMSE_BAG_L2,-0.056257,root_mean_squared_error,168.385671,2220.095410,12.856992,569.012544,2,True,12
8,LightGBMXT_BAG_L1,-0.056408,root_mean_squared_error,82.037572,358.615002,82.037572,358.615002,1,True,1
9,ExtraTreesMSE_BAG_L1,-0.056446,root_mean_squared_error,16.030248,224.040641,16.030248,224.040641,1,True,5
10,NeuralNetFastAI_BAG_L1,-0.056569,root_mean_squared_error,2.919322,471.718552,2.919322,471.718552,1,True,6
11,RandomForestMSE_BAG_L1,-0.056584,root_mean_squared_error,16.823461,235.874209,16.823461,235.874209,1,True,3
12,CatBoost_BAG_L1,-0.059188,root_mean_squared_error,0.124636,49.199661,0.124636,49.199661,1,True,4

In [6]:
# CHECKING BEST MODEL 

best_model = predictor.model_best

print(f'Best Model : {best_model}')

Best Model : WeightedEnsemble_L3

In [7]:
predictor.feature_importance(train_df)

Computing feature importance via permutation shuffling for 24 features using 5000 rows with 5 shuffle sets...
	1174.24s	= Expected runtime (234.85s per shuffle set)
	676.51s	= Actual runtime (Completed 5 of 5 shuffle sets)

,importance,stddev,p_value,n,p99_high,p99_low
curvature,0.087358,0.001762,1.985769e-08,5,0.090986,8.372921e-02
speed_limit,0.081514,0.002045,4.750424e-08,5,0.085725,7.730290e-02
lighting_night,0.070645,0.001213,1.041927e-08,5,0.073142,6.814738e-02
weather_clear,0.024731,0.000541,2.737160e-08,5,0.025844,2.361753e-02
num_reported_accidents,0.013223,0.000820,1.766823e-06,5,0.014912,1.153470e-02
lighting_daylight,0.000857,0.000146,9.751242e-05,5,0.001158,5.560831e-04
lighting_dim,0.000581,0.000087,5.722367e-05,5,0.000760,4.031635e-04
weather_foggy,0.000344,0.000072,2.178865e-04,5,0.000492,1.954884e-04
num_lanes,0.000298,0.000103,1.487725e-03,5,0.000511,8.525132e-05
weather_rainy,0.000287,0.000083,7.470509e-04,5,0.000458,1.165308e-04
holiday_False,0.000176,0.000039,2.612528e-04,5,0.000256,9.666870e-05
holiday_True,0.000137,0.000036,5.250587e-04,5,0.000212,6.293965e-05
public_road_False,0.000118,0.000036,9.506399e-04,5,0.000192,4.312173e-05
time_of_day_evening,0.000105,0.000029,6.291955e-04,5,0.000165,4.536792e-05
public_road_True,0.000093,0.000035,1.995827e-03,5,0.000165,2.112063e-05
road_type_highway,0.000071,0.000036,5.558503e-03,5,0.000144,-2.209883e-06
road_type_rural,0.000068,0.000052,2.191938e-02,5,0.000175,-3.951073e-05
time_of_day_afternoon,0.000057,0.000037,1.371166e-02,5,0.000134,-2.025233e-05
time_of_day_morning,0.000051,0.000045,3.350362e-02,5,0.000144,-4.266823e-05
road_type_urban,0.000043,0.000010,2.928393e-04,5,0.000063,2.287198e-05
road_signs_present_False,0.000036,0.000021,9.949121e-03,5,0.000080,-8.184577e-06
road_signs_present_True,0.000031,0.000009,6.333591e-04,5,0.000049,1.350037e-05
school_season_False,0.000030,0.000011,1.595156e-03,5,0.000052,8.275395e-06
school_season_True,0.000023,0.000011,4.429753e-03,5,0.000045,7.740323e-07

In [8]:
# CHECK SUBMISSION

# TEST DATA PREDICTION
y_pred = predictor.predict(test_df)

submission = pd.read_csv(r'/kaggle/input/playground-series-s5e10/sample_submission.csv')

submission['accident_risk'] = y_pred

submission

            id  accident_risk
0       517754       0.296163
1       517755       0.123493
2       517756       0.185023
3       517757       0.315282
4       517758       0.405987
...        ...            ...
172580  690334       0.103720
172581  690335       0.518612
172582  690336       0.247703
172583  690337       0.128081
172584  690338       0.486580

[172585 rows x 2 columns]

In [9]:
# GET OOF (OUT-OF-FOLD) PREDICTION

# GET OOF
oof_predictions = predictor.predict_oof()

# CONVERT TO DATAFRAME
y_pred = oof_predictions.to_frame(name = 'oof_prediction')  # ---> RETURN DATAFRAME
oof_df = pd.DataFrame(y_pred)

oof_df

        oof_prediction
0             0.128537
1             0.324044
2             0.388761
3             0.131379
4             0.469125
...                ...
517749        0.319166
517750        0.242902
517751        0.293293
517752        0.492509
517753        0.191504

[517754 rows x 1 columns]

In [10]:
# SAVE PREDICTED DATA
submission.to_csv(r'submission.csv', index = False)
oof_df.to_csv(r'oof_data_autogluon1.csv', index = False)